@startuml Blackjack

class Main {
}

class Game {
  -Deck deck
  -Player player
  -Dealer dealer
  +__construct()
  +getDeck()
  +getPlayer()
  +getDealer()
  +start()
  +showStartMesssage()

}

class Player {
  -INIT_NUM_OF_CARDS_IN_HAND
  -array hand
  -int scoreTotal
  -string status
  +__construct()
  +getHand()
  +getScoreTotal()
  +getStatus()
  +initHand()
  +drawACard()
  -calcScoreTotal()
  +changeStatus()
}

class Dealer {
  +checkBurst()
  +judgeWinOrLose()
  +drawAfterAllPlayerStand()
}

class Deck {
  -array deck
  +__construct()
  +getDeck()
  +initDeck()
  +takeACard()
}

class Card {
  -CARD_SCORE
  -array suits
  +createNewDeck()
}

Main -- Game
Game -- Deck
Game -- Player
Deck -- Card

Player <|-- Dealer

@enduml
