@startuml Blackjack

class Game {
  -Deck deck
  -Dealer dealer
  -array<int,Player> players

  +__construct()
  +play()
  -set()
  -start()
  -action()
  -result()
  -end()
}

class Deck {
  -array<int,array<string,int|string>> deck

  +__construct()
  +getDeck()
  +initDeck()
  +takeACard()
}

class Card {
  -CARD_SCORE

  -array suits
  +createNewDeck()
}

class Dealer {
  -NUM_OF_FIRST_HAND
  -DealerPlayer dealerPlayer

  +__construct()
  +getDealerPlayer()
  +dealOutFirstHand()
  +dealOneCard()
  +checkBurst()
  +judgeWinOrLose()
  -hasStand()
  -compareScoreTotal()
}

abstract Player {
  -string name
  -array<int,array<string,int|string>> hand
  -int scoreTotal
  -int countAce
  -string status

  +{abstract} action()
  +{abstract} selectHitOrStand()

  +__construct()
  +getName()
  +getHand()
  +getScoreTotal()
  +getStatus()
  +addACardToHand()
  +calcScoreTotal()
  -calcAceScore()
  +changeStatus()
}

class DealerPlayer {
  +action()
  +selectHitOrStand()
}

class ManualPlayer {
  +action()
  +selectHitOrStand()
}

class AutoPlayer {
  +action()
  +selectHitOrStand()
}

class Message {
  +getSettingMessage()
  +getInputNumOfPlayerMessage()
  +getSettingInputErrorMessage()

  +getStartMessage()
  +getFirstHandMessage()
  +getDealerFirstHandMessage()
  +getLoseByBurstMessage()

  +getProgressMessage()
  +getProgressQuestionMessage()
  +getCardDrawnMessage()
  +getInputErrorMessage()

  +getScoreTotalResultMessage()
  +getStandMessage()
  +getDealerBurstMessage()
  +getWinByBurstMessage()
  +getResultMessage()

  +getEndMessage()
}

Game -- Deck
Deck *-- Card
Game -- Dealer
Dealer *-- DealerPlayer
Game -- Player
Game --- ManualPlayer
Game --- AutoPlayer
Player <|-- DealerPlayer
Player <|-- ManualPlayer
Player <|-- AutoPlayer
Game -- Message

@enduml
