@startuml Blackjack

skinparam responseMessageBelowArrow true
skinparam actorStyle awesome

participant Main order 10
participant Game order 20
participant Message order 30
actor Dealer order 40
actor "<<Manual>>\nPlayer" as mp order 50 #AliceBlue
actor "<<Auto>>\nPlayer" as ap order 60 #LavenderBlush
participant Deck order 70
participant Card order 80

Main -> Game : Game を new する

group #LightGoldenRodYellow Game を new する
  activate Game
  Game ->  Dealer : Dealer を new する
  activate  Dealer
  Dealer -> Deck : Deck を new する
  activate Deck
  Deck -> Card : カード52枚を取得する
  activate Card
  Card --> Deck : カード52枚を返却する
  deactivate Card

  Game -> mp : Player を new する
  activate mp #AliceBlue
end

Main -> Game : ブラックジャックを\n開始する

group #LightGoldenRodYellow ゲームの設定をする
  Game -> Message : プレイヤー数を決める(メッセージ表示)
  note over Message
  ブラックジャックの設定をします。
  プレイヤーの人数を選んでください。（1, 2, 3）
  end note

  Game -> ap : 決めた人数の NPC を new する
  activate ap #LavenderBlush
end

group #LightGoldenRodYellow ベットする額を決める
  Game -> Message : ベットする額を決める(メッセージ表示)
  note over Message
  『プレイスユアベット』
  あなたの持っているチップは100ドルです。
  ベットする額を決めてください。（1〜1000ドル）
  end note
  Game -> mp : Player の ベットする額 を決めた額に変更する
end

group #LightGoldenRodYellow ゲームを開始する
  Game -> Dealer : デッキをシャッフルする
  Dealer -> Deck : デッキをシャッフルする

  Dealer -> Deck : デッキからプレイヤーに手札2枚を配る
  Deck --> mp

  Dealer -> Deck : デッキから NPC に手札2枚を配る
  Deck --> ap

  Dealer -> Deck : デッキから ディーラー に手札2枚を配る
  Deck --> Dealer

  Game ->  Message : ブラックジャックの開始時の\nメッセージを表示する

  note over Message
    ブラックジャックを開始します。
    あなたの引いたカードはハートの7です。
    あなたの引いたカードはクラブの8です。
    ディーラーの引いたカードはダイヤのQです。
    ディーラーの引いた2枚目のカードはわかりません。
    あなたの現在の得点は15です。カードを引きますか？（Y/N）
  end note

end

group #LightGoldenRodYellow ゲームを進行する

  group #AliceBlue Player(あなた)は Hit か Stand かを選択する
    alt Y (Hit)
      Game -> mp : プレイヤーは1枚カードを引く
      mp -> Deck : 1枚カードを引く
      Deck --> mp : 1枚カードを返す
      mp -> mp : 得点を計算する

      Game -> Dealer : ディーラーはバーストか否かチェックする
      Dealer -> mp : バーストか否かチェックする

      alt カードの合計値が 21 を超えていない場合
        Dealer --> Game :

        Game ->  Message : メッセージを表示する
        note over Message
          あなたの引いたカードはスペードの５です。
          あなたの現在の得点は20です。カードを引きますか？（Y/N）
        end note
      else Burst (カードの合計値が 21 を超えていた場合)
        Dealer -> mp : ステータスを\n「burst」に変更する
        Dealer --> Game :

      end
    else N (Stand)

      Game ->  Message : メッセージを表示する
      note over Message
        あなたの引いた2枚目のカードはダイヤの2でした。
        あなたの現在の得点は12です。
      end note

      Game -> mp : ステータスを\n「stand」に変更する

    else 再入力
      Game ->  Message : メッセージを表示する
      note over Message
        Y/N で入力してください。カードを引きますか？（Y/N）
      end note
      Game -> Game : 再入力
    end

    alt Burst (プレイヤーのカードの合計値が 21 を超えていた場合)

      Game ->  Message : メッセージを表示する
      note over Message #Yellow
        あなたの引いたカードはダイヤのJです。
        あなたの現在の得点は25です。
        合計値が21を超えたので、あなたの負けです。
      end note
    end
  end

  group #LavenderBlush NPC(NPC1, NPC2)がいれば Hit か Stand かを選択する（自動）
    alt Y (Hit)
      Game -> ap : NPC は1枚カードを引く
      ap -> Deck : 1枚カードを引く
      Deck --> ap : 1枚カードを返す
      ap -> ap : 得点を計算する

      Game -> Dealer : ディーラーはバーストか否かチェックする
      Dealer -> ap : バーストか否かチェックする

      alt カードの合計値が 21 を超えていない場合
        Dealer --> Game :
        Game ->  Message : メッセージを表示する
        note over Message
          NPC の引いたカードはスペードの５です。
          NPC の現在の得点は20です。カードを引きますか？（Y/N）
        end note
      else Burst (カードの合計値が 21 を超えていた場合)
        Dealer -> ap : ステータスを\n「burst」に変更する
        Dealer --> Game :

      end
    else N (Stand)

      Game ->  Message : メッセージを表示する
      note over Message
        NPC の引いた2枚目のカードはダイヤの2でした。
        NPC の現在の得点は12です。
      end note

      Game -> ap : ステータスを\n「stand」に変更する

    else 再入力
      Game ->  Message : メッセージを表示する
      note over Message
        Y/N で入力してください。カードを引きますか？（Y/N）
      end note
      Game -> Game : 再入力
    end

    alt Burst (プNPC カードの合計値が 21 を超えていた場合)
      Game ->  Message : メッセージを表示する
      note over Message #Yellow
        NPC の引いたカードはダイヤのJです。
        NPC の現在の得点は25です。
        合計値が21を超えたので、 NPC の負けです。
      end note
    end
  end

end

group #LightGoldenRodYellow 結果を判定する
  alt Stand (カードの合計値が 21 以下) のプレイヤーが残っていた場合

      Game -> Dealer : ディーラーは自分のカードの合計値が\n 17 以上になるまで引き続ける
    loop
      Dealer -> Deck : 1枚カードを引く
      Deck --> Dealer : 1枚カードを返す
      Dealer -> Dealer : 得点を計算する
      Dealer -> Dealer : ステータスを変更する
      Dealer ->  Message : メッセージを表示する
      note over Message
        ディーラーの引いたカードはハートのKです。
      end note
    end

    alt Burst (ディーラーのカードの合計値が 21 を超えていた場合)
      Dealer ->  Message : メッセージを表示する
      note over Message #Yellow
        ディーラーの得点は22です。
        合計値が21を超えたので、ディーラーはバーストしました。
        あなたの勝ちです！
        （NPCの勝ちです！）
      end note

    else ディーラーのカードの合計値が 21 を超えていない場合

      Dealer -> Dealer : 勝敗を判定する
      Dealer -> Dealer : スコアを取得する
      Dealer -> mp : スコアを取得する
      Dealer -> mp : ステータスを\nwin, lose, draw に変更する
      Dealer -> ap : ステータスを\nwin, lose, draw に変更する

      Dealer ->  Message : メッセージを表示する
      note over Message #Yellow
        あなたの勝ちです！
        （NPCの勝ちです！）
        ブラックジャックを終了します。
      end note
    end
  end
end


group #LightGoldenRodYellow チップを計算する
    Game -> Dealer : ディーラーはチップを計算する
    Dealer -> mp : Player の合計チップ数を変更する

    alt 勝った人（ステータス → win）
      Dealer ->  Message : メッセージを表示する
      note over Message #Yellow
        勝ったので 5 チップと同額の配当を得られます。
        あなたのチップ残高は 105 ドルです。
      end note

    else 負けた人（ステータス → lose）
      Dealer ->  Message : メッセージを表示する
      note over Message #Yellow
        負けたため、チップ 5 ドルは没収されます。
        あなたのチップ残高は 95 ドルです。
      end note
    else 引き分けた人（ステータス → draw）
      Dealer ->  Message : メッセージを表示する
      note over Message #Yellow
        引き分けたため、チップ 5 ドルはそのままです。
        あなたのチップ残高は 100 ドルです。
      end note
    end
end

Game --> Main : ゲーム終了
  deactivate Dealer
  deactivate mp
  deactivate ap
  deactivate Deck
deactivate Game
@enduml
