@startuml Blackjack

title ブラックジャックゲーム全体の流れ

skinparam responseMessageBelowArrow true
skinparam actorStyle awesome

participant Main order 10
participant Game order 20
actor Dealer order 30
participant Deck order 40
participant Card order 50
actor "<<Manual>>\nPlayer" as mp order 60 #AliceBlue
actor "<<Auto>>\nPlayer" as ap order 70 #LavenderBlush

Main -> Game : Game を new する

group #LightGoldenRodYellow Game を new する
  activate Game
  Game ->  Dealer : Dealer を new する
  activate  Dealer
  Game -> Deck : Deck を new する
  activate Deck
  Deck -> Card : カード52枚を取得する
  activate Card
  Card --> Deck : カード52枚を返却する
  deactivate Card

  Game -> mp : Player を new する
  activate mp #AliceBlue
end

Main -> Game : ブラックジャックを\n開始する

group #LightGoldenRodYellow ゲームの設定をする
  note right Game #Black
  <font color="white">ブラックジャックの設定をします。
  <font color="white">プレイヤーの人数を入力してください。（1〜3）
  <font color="white">🙋‍ 2
  <font color="white">プレイヤー2名でゲームを開始します。
  end note

  Game -> ap : 決めた人数の NPC を new する
  activate ap #LavenderBlush
end

group #LightGoldenRodYellow ベットする額を決める
  note right Game #Black
  <font color="white">あなたの持っているチップは100ドルです。
  <font color="white">ベットする額を入力してください。（1〜1000ドル）
  <font color="white">💲 10
  <font color="white">10ドルをベットしました。
  end note
  Game -> mp : Player の ベットする額 を決めた額に変更する
end

ref over Game
  別添「１ゲームの流れ」
  ・ゲームを開始する
  ・ゲームを進行する
  ・結果を判定する
end ref

group #LightGoldenRodYellow チップを計算する
    Game -> Dealer : ディーラーはチップを計算する
    Dealer -> mp : Player の合計チップ数を変更する

    alt 勝った人（ステータス → win）
      note right Game #Black
        <font color="white">勝ったので 5 チップと同額の配当を得られます。
        <font color="white">あなたのチップ残高は 105 ドルです。
      end note

    else 負けた人（ステータス → lose）
      note right Game #Black
        <font color="white">負けたため、チップ 5 ドルは没収されます。
        <font color="white">あなたのチップ残高は 95 ドルです。
      end note
    else 引き分けた人（ステータス → draw）
      note right Game #Black
        <font color="white">引き分けたため、チップ 5 ドルはそのままです。
        <font color="white">あなたのチップ残高は 100 ドルです。
      end note
    end
end

group #LightGoldenRodYellow ゲームを続けるか、やめるかを選択する

    alt チップ残高がある場合
      note right Game #Black
        <font color="white">ブラックジャックゲームを続けますか？（Y/N）
      end note
    else チップ残高が 0 の場合
      note right Game #Black
        <font color="white">あなたは、チップの残高がなくなりました。
      end note
    end
end
alt ゲーム続行
  note over Game
    次のゲームへ
    （「ベットする額を決める」まで戻る）
  end note
else ゲーム終了
  Game --> Main : ゲーム終了
end
  deactivate Dealer
  deactivate mp
  deactivate ap
  deactivate Deck
deactivate Game
@enduml
