@startuml Blackjack

title 別添「１ゲームの流れ」

skinparam responseMessageBelowArrow true
skinparam actorStyle awesome

participant Main order 10
participant Game order 20
participant Message order 30
actor Dealer order 40
actor "<<Manual>>\nPlayer" as mp order 50 #AliceBlue
actor "<<Auto>>\nPlayer" as ap order 60 #LavenderBlush
participant Deck order 70
participant Card order 80

group #LightGoldenRodYellow ゲームを開始する
  Game -> Dealer : デッキをシャッフルする
  Dealer -> Deck : デッキをシャッフルする

  Dealer -> Deck : デッキからプレイヤーに手札2枚を配る
  Deck --> mp

  Dealer -> Deck : デッキから NPC に手札2枚を配る
  Deck --> ap

  Dealer -> Deck : デッキから ディーラー に手札2枚を配る
  Deck --> Dealer

  note right Game #Black
    <font color="white">ブラックジャックを開始します。</font>
    <font color="white">あなたの引いたカードはハートの7です。</font>
    <font color="white">あなたの引いたカードはクラブの8です。</font>

    <font color="white">ディーラーの引いたカードはダイヤのQです。</font>
    <font color="white">ディーラーの引いた2枚目のカードはわかりません。</font>

    <font color="white">あなたの現在の得点は15です。カードを引きますか？（Y/N）</font>
  end note

end

group #LightGoldenRodYellow ゲームを進行する

  activate Dealer
  activate mp #AliceBlue
  activate ap #LavenderBlush
  activate Deck
  activate Game

  group #AliceBlue Player(あなた)は Hit か Stand かを選択する
    alt Y (Hit)
      Game -> mp : プレイヤーは1枚カードを引く
      mp -> Deck : 1枚カードを引く
      Deck --> mp : 1枚カードを返す
      mp -> mp : 得点を計算する

      Game -> Dealer : ディーラーはバーストか否かチェックする
      Dealer -> mp : バーストか否かチェックする

      alt カードの合計値が 21 を超えていない場合
        Dealer --> Game :

        note right Game #Black
          <font color="white">あなたの引いたカードはスペードの５です。</font>
          <font color="white">あなたの現在の得点は20です。カードを引きますか？（Y/N）</font>
        end note
      else Burst (カードの合計値が 21 を超えていた場合)
        Dealer -> mp : ステータスを\n「burst」に変更する
        Dealer --> Game :

      end
    else N (Stand)

      note right Game #Black
        <font color="white">あなたの引いた2枚目のカードはダイヤの2でした。</font>
        <font color="white">あなたの現在の得点は12です。</font>
      end note

      Game -> mp : ステータスを\n「stand」に変更する

    else 再入力
      note right Game #Black
        <font color="white">Y/N で入力してください。カードを引きますか？（Y/N）</font>
      end note
      Game -> Game : 再入力
    end

    alt Burst (プレイヤーのカードの合計値が 21 を超えていた場合)

      note right Game #Black
        <font color="white">あなたの引いたカードはダイヤのJです。</font>
        <font color="white">あなたの現在の得点は25です。</font>
        <font color="white">合計値が21を超えたので、あなたの負けです。</font>
      end note
    end
  end

  group #LavenderBlush NPC(NPC1, NPC2)がいれば Hit か Stand かを選択する（自動）
    alt Y (Hit)
      Game -> ap : NPC は1枚カードを引く
      ap -> Deck : 1枚カードを引く
      Deck --> ap : 1枚カードを返す
      ap -> ap : 得点を計算する

      Game -> Dealer : ディーラーはバーストか否かチェックする
      Dealer -> ap : バーストか否かチェックする

      alt カードの合計値が 21 を超えていない場合
        Dealer --> Game :
        note right Game #Black
          <font color="white">NPC の引いたカードはスペードの５です。</font>
          <font color="white">NPC の現在の得点は20です。カードを引きますか？</font>（Y/N）
        end note
      else Burst (カードの合計値が 21 を超えていた場合)
        Dealer -> ap : ステータスを\n「burst」に変更する
        Dealer --> Game :

      end
    else N (Stand)

      note right Game #Black
        <font color="white">NPC の引いた2枚目のカードはダイヤの2でした。</font>
        <font color="white">NPC の現在の得点は12です。</font>
      end note

      Game -> ap : ステータスを\n「stand」に変更する

    else 再入力
      note right Game #Black
        <font color="white">Y/N で入力してください。カードを引きますか？（Y/N）</font>
      end note
      Game -> Game : 再入力
    end

    alt Burst (NPC カードの合計値が 21 を超えていた場合)
      note right Game #Black
        <font color="white">NPC の引いたカードはダイヤのJです。</font>
        <font color="white">NPC の現在の得点は25です。</font>
        <font color="white">合計値が21を超えたので、 NPC の負けです。</font>
      end note
    end
  end

end

group #LightGoldenRodYellow 結果を判定する
  alt Stand (カードの合計値が 21 以下) のプレイヤーが残っていた場合

      Game -> Dealer : ディーラーは自分のカードの合計値が\n 17 以上になるまで引き続ける
    loop
      Dealer -> Deck : 1枚カードを引く
      Deck --> Dealer : 1枚カードを返す
      Dealer -> Dealer : 得点を計算する
      Dealer -> Dealer : ステータスを変更する
      note right Game #Black
        <font color="white">ディーラーの引いたカードはハートのKです。</font>
      end note
    end

    alt Burst (ディーラーのカードの合計値が 21 を超えていた場合)
      note right Game #Black
        <font color="white">ディーラーの得点は22です。</font>
        <font color="white">合計値が21を超えたので、ディーラーはバーストしました。</font>
        <font color="white">あなたの勝ちです！🎉</font>
        <font color="white">（NPCの勝ちです！🎉）</font>
      end note

    else ディーラーのカードの合計値が 21 を超えていない場合

      Dealer -> Dealer : 勝敗を判定する
      Dealer -> Dealer : スコアを取得する
      Dealer -> mp : スコアを取得する
      Dealer -> mp : ステータスを\nwin, lose, draw に変更する
      Dealer -> ap : ステータスを\nwin, lose, draw に変更する

      note right Game #Black
        <font color="white">あなたの勝ちです！🎉</font>
        <font color="white">（NPCの勝ちです！🎉）</font>
      end note
    end
  end
end

deactivate Dealer
deactivate mp
deactivate ap
deactivate Deck
deactivate Game
@enduml
